services:
  postgres:
    image: postgres:15
    container_name: postgres_eduplay
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Base de datos por defecto para conexión inicial
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      # Script para crear múltiples bases de datos
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - n8n_network

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    depends_on:
      - postgres
      - ollama
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: postgres
      DB_POSTGRESDB_DATABASE: n8n
      GENERIC_TIMEZONE: America/Lima

      # Credenciales de acceso a la UI de n8n
      N8N_BASIC_AUTH_ACTIVE: true
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: admin123

      # Configuración de red pública
      N8N_HOST: localhost
      N8N_PORT: 5678
      WEBHOOK_URL: http://localhost:5678/
      # URL dentro de la red Docker
      OLLAMA_URL: http://ollama:11434
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - n8n_network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    networks:
      - n8n_network

networks:
  n8n_network:
    driver: bridge
